services:
  - type: web
    name: zeptrax-ai-edutech
    runtime: python
    buildCommand: ""
    startCommand: "python Zeptrax_AI_Edutech/serve_app.py"
    envVars:
      - key: PORT
        value: 8000
